all: 
	pdflatex main.tex && pdflatex main.tex && pdflatex main.tex

clean:
	rm -rf $(shell find . -name "*.aux") $(shell find . -name "*.log") $(shell find . -name "*.pdf") $(shell find . -name "*.toc") $(shell find . -name "*.out")